Update Icons to v1.11.3
isosphere/yew-bootstrap pull request #42
Opened 2024-04-06 09:16 UTC by alexkazik

Updates the included/referenced bootstrap-icons version.

Changes to the generated icons:
```diff
--- bootstrap_icons_generated-v1.10.5.rs	2024-04-06 11:03:32
+++ bootstrap_icons_generated-v1.11.3.rs	2024-04-06 11:05:37
@@ -56,7 +56,10 @@
     pub const ALIGN_START: BI = BI("<i class=\"bi bi-align-start\"></i>");
     pub const ALIGN_TOP: BI = BI("<i class=\"bi bi-align-top\"></i>");
     pub const ALIPAY: BI = BI("<i class=\"bi bi-alipay\"></i>");
+    pub const ALPHABET: BI = BI("<i class=\"bi bi-alphabet\"></i>");
+    pub const ALPHABET_UPPERCASE: BI = BI("<i class=\"bi bi-alphabet-uppercase\"></i>");
     pub const ALT: BI = BI("<i class=\"bi bi-alt\"></i>");
+    pub const AMAZON: BI = BI("<i class=\"bi bi-amazon\"></i>");
     pub const AMD: BI = BI("<i class=\"bi bi-amd\"></i>");
     pub const ANDROID: BI = BI("<i class=\"bi bi-android\"></i>");
     pub const ANDROID2: BI = BI("<i class=\"bi bi-android2\"></i>");
@@ -126,12 +129,16 @@
     pub const ARROW_UP_SHORT: BI = BI("<i class=\"bi bi-arrow-up-short\"></i>");
     pub const ARROW_UP_SQUARE: BI = BI("<i class=\"bi bi-arrow-up-square\"></i>");
     pub const ARROW_UP_SQUARE_FILL: BI = BI("<i class=\"bi bi-arrow-up-square-fill\"></i>");
+    pub const ARROWS: BI = BI("<i class=\"bi bi-arrows\"></i>");
     pub const ARROWS_ANGLE_CONTRACT: BI = BI("<i class=\"bi bi-arrows-angle-contract\"></i>");
     pub const ARROWS_ANGLE_EXPAND: BI = BI("<i class=\"bi bi-arrows-angle-expand\"></i>");
     pub const ARROWS_COLLAPSE: BI = BI("<i class=\"bi bi-arrows-collapse\"></i>");
+    pub const ARROWS_COLLAPSE_VERTICAL: BI = BI("<i class=\"bi bi-arrows-collapse-vertical\"></i>");
     pub const ARROWS_EXPAND: BI = BI("<i class=\"bi bi-arrows-expand\"></i>");
+    pub const ARROWS_EXPAND_VERTICAL: BI = BI("<i class=\"bi bi-arrows-expand-vertical\"></i>");
     pub const ARROWS_FULLSCREEN: BI = BI("<i class=\"bi bi-arrows-fullscreen\"></i>");
     pub const ARROWS_MOVE: BI = BI("<i class=\"bi bi-arrows-move\"></i>");
+    pub const ARROWS_VERTICAL: BI = BI("<i class=\"bi bi-arrows-vertical\"></i>");
     pub const ASPECT_RATIO: BI = BI("<i class=\"bi bi-aspect-ratio\"></i>");
     pub const ASPECT_RATIO_FILL: BI = BI("<i class=\"bi bi-aspect-ratio-fill\"></i>");
     pub const ASTERISK: BI = BI("<i class=\"bi bi-asterisk\"></i>");
@@ -139,6 +146,14 @@
     pub const AWARD: BI = BI("<i class=\"bi bi-award\"></i>");
     pub const AWARD_FILL: BI = BI("<i class=\"bi bi-award-fill\"></i>");
     pub const BACK: BI = BI("<i class=\"bi bi-back\"></i>");
+    pub const BACKPACK: BI = BI("<i class=\"bi bi-backpack\"></i>");
+    pub const BACKPACK_FILL: BI = BI("<i class=\"bi bi-backpack-fill\"></i>");
+    pub const BACKPACK2: BI = BI("<i class=\"bi bi-backpack2\"></i>");
+    pub const BACKPACK2_FILL: BI = BI("<i class=\"bi bi-backpack2-fill\"></i>");
+    pub const BACKPACK3: BI = BI("<i class=\"bi bi-backpack3\"></i>");
+    pub const BACKPACK3_FILL: BI = BI("<i class=\"bi bi-backpack3-fill\"></i>");
+    pub const BACKPACK4: BI = BI("<i class=\"bi bi-backpack4\"></i>");
+    pub const BACKPACK4_FILL: BI = BI("<i class=\"bi bi-backpack4-fill\"></i>");
     pub const BACKSPACE: BI = BI("<i class=\"bi bi-backspace\"></i>");
     pub const BACKSPACE_FILL: BI = BI("<i class=\"bi bi-backspace-fill\"></i>");
     pub const BACKSPACE_REVERSE: BI = BI("<i class=\"bi bi-backspace-reverse\"></i>");
@@ -183,6 +198,8 @@
     pub const BALLOON_FILL: BI = BI("<i class=\"bi bi-balloon-fill\"></i>");
     pub const BALLOON_HEART: BI = BI("<i class=\"bi bi-balloon-heart\"></i>");
     pub const BALLOON_HEART_FILL: BI = BI("<i class=\"bi bi-balloon-heart-fill\"></i>");
+    pub const BAN: BI = BI("<i class=\"bi bi-ban\"></i>");
+    pub const BAN_FILL: BI = BI("<i class=\"bi bi-ban-fill\"></i>");
     pub const BANDAID: BI = BI("<i class=\"bi bi-bandaid\"></i>");
     pub const BANDAID_FILL: BI = BI("<i class=\"bi bi-bandaid-fill\"></i>");
     pub const BANK: BI = BI("<i class=\"bi bi-bank\"></i>");
@@ -210,6 +227,7 @@
     pub const BEZIER: BI = BI("<i class=\"bi bi-bezier\"></i>");
     pub const BEZIER2: BI = BI("<i class=\"bi bi-bezier2\"></i>");
     pub const BICYCLE: BI = BI("<i class=\"bi bi-bicycle\"></i>");
+    pub const BING: BI = BI("<i class=\"bi bi-bing\"></i>");
     pub const BINOCULARS: BI = BI("<i class=\"bi bi-binoculars\"></i>");
     pub const BINOCULARS_FILL: BI = BI("<i class=\"bi bi-binoculars-fill\"></i>");
     pub const BLOCKQUOTE_LEFT: BI = BI("<i class=\"bi bi-blockquote-left\"></i>");
@@ -293,6 +311,7 @@
     pub const BRIGHTNESS_HIGH_FILL: BI = BI("<i class=\"bi bi-brightness-high-fill\"></i>");
     pub const BRIGHTNESS_LOW: BI = BI("<i class=\"bi bi-brightness-low\"></i>");
     pub const BRIGHTNESS_LOW_FILL: BI = BI("<i class=\"bi bi-brightness-low-fill\"></i>");
+    pub const BRILLIANCE: BI = BI("<i class=\"bi bi-brilliance\"></i>");
     pub const BROADCAST: BI = BI("<i class=\"bi bi-broadcast\"></i>");
     pub const BROADCAST_PIN: BI = BI("<i class=\"bi bi-broadcast-pin\"></i>");
     pub const BROWSER_CHROME: BI = BI("<i class=\"bi bi-browser-chrome\"></i>");
@@ -336,6 +355,10 @@
     pub const C_CIRCLE_FILL: BI = BI("<i class=\"bi bi-c-circle-fill\"></i>");
     pub const C_SQUARE: BI = BI("<i class=\"bi bi-c-square\"></i>");
     pub const C_SQUARE_FILL: BI = BI("<i class=\"bi bi-c-square-fill\"></i>");
+    pub const CAKE: BI = BI("<i class=\"bi bi-cake\"></i>");
+    pub const CAKE_FILL: BI = BI("<i class=\"bi bi-cake-fill\"></i>");
+    pub const CAKE2: BI = BI("<i class=\"bi bi-cake2\"></i>");
+    pub const CAKE2_FILL: BI = BI("<i class=\"bi bi-cake2-fill\"></i>");
     pub const CALCULATOR: BI = BI("<i class=\"bi bi-calculator\"></i>");
     pub const CALCULATOR_FILL: BI = BI("<i class=\"bi bi-calculator-fill\"></i>");
     pub const CALENDAR: BI = BI("<i class=\"bi bi-calendar\"></i>");
@@ -632,6 +655,8 @@
     pub const CONE: BI = BI("<i class=\"bi bi-cone\"></i>");
     pub const CONE_STRIPED: BI = BI("<i class=\"bi bi-cone-striped\"></i>");
     pub const CONTROLLER: BI = BI("<i class=\"bi bi-controller\"></i>");
+    pub const COOKIE: BI = BI("<i class=\"bi bi-cookie\"></i>");
+    pub const COPY: BI = BI("<i class=\"bi bi-copy\"></i>");
     pub const CPU: BI = BI("<i class=\"bi bi-cpu\"></i>");
     pub const CPU_FILL: BI = BI("<i class=\"bi bi-cpu-fill\"></i>");
     pub const CREDIT_CARD: BI = BI("<i class=\"bi bi-credit-card\"></i>");
@@ -641,6 +666,8 @@
     pub const CREDIT_CARD_2_FRONT_FILL: BI = BI("<i class=\"bi bi-credit-card-2-front-fill\"></i>");
     pub const CREDIT_CARD_FILL: BI = BI("<i class=\"bi bi-credit-card-fill\"></i>");
     pub const CROP: BI = BI("<i class=\"bi bi-crop\"></i>");
+    pub const CROSSHAIR: BI = BI("<i class=\"bi bi-crosshair\"></i>");
+    pub const CROSSHAIR2: BI = BI("<i class=\"bi bi-crosshair2\"></i>");
     pub const CUP: BI = BI("<i class=\"bi bi-cup\"></i>");
     pub const CUP_FILL: BI = BI("<i class=\"bi bi-cup-fill\"></i>");
     pub const CUP_HOT: BI = BI("<i class=\"bi bi-cup-hot\"></i>");
@@ -731,6 +758,8 @@
     pub const DROPLET: BI = BI("<i class=\"bi bi-droplet\"></i>");
     pub const DROPLET_FILL: BI = BI("<i class=\"bi bi-droplet-fill\"></i>");
     pub const DROPLET_HALF: BI = BI("<i class=\"bi bi-droplet-half\"></i>");
+    pub const DUFFLE: BI = BI("<i class=\"bi bi-duffle\"></i>");
+    pub const DUFFLE_FILL: BI = BI("<i class=\"bi bi-duffle-fill\"></i>");
     pub const EAR: BI = BI("<i class=\"bi bi-ear\"></i>");
     pub const EAR_FILL: BI = BI("<i class=\"bi bi-ear-fill\"></i>");
     pub const EARBUDS: BI = BI("<i class=\"bi bi-earbuds\"></i>");
@@ -747,12 +776,18 @@
     pub const EJECT_FILL: BI = BI("<i class=\"bi bi-eject-fill\"></i>");
     pub const EMOJI_ANGRY: BI = BI("<i class=\"bi bi-emoji-angry\"></i>");
     pub const EMOJI_ANGRY_FILL: BI = BI("<i class=\"bi bi-emoji-angry-fill\"></i>");
+    pub const EMOJI_ASTONISHED: BI = BI("<i class=\"bi bi-emoji-astonished\"></i>");
+    pub const  [...]

2024-04-06 15:25 UTC, isosphere requested changes
Update looks good; but since every such update will be complicated by this path change - I think we might as well make this the last "breaking" update to icons by removing the reference to the version number in the directory.

2024-04-06 15:25 UTC, isosphere commented on examples/icons/index.html
> +    <link rel="stylesheet" href="bootstrap-icons-v1.11.3/bootstrap-icons.css"/>
Perhaps we should not put the version in the directory; it is already in the header of the file.

2024-04-06 15:25 UTC, isosphere commented on packages/yew-bootstrap/bootstrap-icons-v1.11.3/bootstrap-icons.css
> + * Bootstrap Icons v1.11.3 (https://icons.getbootstrap.com/)
The version is identified here, so no need to identify it in the directory and complicate things.

2024-04-06 16:41 UTC, alexkazik commented
I agree that it's not a good idea to manually change the version in the path when upgrading this package.

The downside of removing the version from the path I see is that trunk does not apply the hash-renaming and thus a new version would be at the same path and a browser might think it's version is still accurate and thus not load it again.

I've added a commit which generates the link automatically.

If you prefer to remove the version from the path, I'll do that.

2024-04-07 07:52 UTC, alexkazik commented
I've updated the branch with better code.
Also there is now an option to move all the generating code into the library.
Depending on what you prefer, I'll:
- remove the last two commits and remove the version from the directory
- remove the last commit (in the example)
- merge the last two commits (in the library)

2024-06-12 15:25 UTC, isosphere requested changes
Appologizes, I never submitted this review. I didn't realize that the comments were invisible until I did so. 

Double apologies in that this review is probably annoying for you, especially after this delay. Generalizing this solution seems to be a problem that others are having, as mentioned above.

2024-06-12 15:25 UTC, isosphere commented on examples/icons/src/bin/link-bootstrap-icons.rs
> +        }
I'm having trouble understanding what this looping is for, could you please explain it?

2024-06-12 15:25 UTC, isosphere commented on examples/icons/src/bin/link-bootstrap-icons.rs
> +        std::env::var("TRUNK_SOURCE_DIR").expect("Environment variable TRUNK_SOURCE_DIR"),
Looks like this environment variable gets automatically set when running with trunk, cool beans. We might be screwing over people that use wasm-pack or something.

2024-06-12 15:25 UTC, isosphere commented on packages/yew-bootstrap/src/icons/mod.rs
> +            }
I think this looping is going a level deeper until it finds the target directory. I don't love this experimental approach, crawling the user's file system. It won't always work either: for example, on my systems I use this in my `~/.cargo/config`:

```
[build]
target-dir = "/home/matt/.cargo/build"
```

Meaning that my target directory is always under that shared directory, regardless of where I compile something. This build script will never find it. 

Looks like this is a common problem: https://github.com/rust-lang/cargo/issues/9661

2024-06-13 16:13 UTC, alexkazik commented
No worries about the delay, though I was beginning to wonder.

Good point about the target folder, and I didn't even know it existed.
(I didn't invent the idea, just copied it as I saw it matching.)

Unfortunately there is no option in trunk to include the output of a command into the html.

I think this means that I should remove the last commit (the move this into the lib).

And leaves us with a few options:
- keep the second commit and keep the "auto finding" in the examples, but add a few comments about the problem
- remove that commit also (only 1 left) and
- - keep it as is (requires to change the version in the index.html each icons update)
- - remove the version from the path, which may has the problem of caching, as the files would now always have the same name and the name
- - do something else, though I don't know what

2024-06-17 16:48 UTC, isosphere commented
How about we include the generated file with each release, and rather than make a build script for generating these files we instead have a github action for it. We can control the environment of the runner for that action (i.e.: we can ensure the target directory will be found). The action will reside in our source tree, so folks can steal it if they want to DIY the generation.

I agree with your concerns around caching; it's probably best to have the version in the filename.

2024-06-17 20:44 UTC, isosphere commented on examples/icons/index.html
> +    <link rel="stylesheet" href="bootstrap-icons-v1.11.3/bootstrap-icons.css"/>
I disagree with myself now re: caching

2024-06-17 20:45 UTC, alexkazik commented
> How about we include the generated file with each release, and rather than make a build script for generating these files we instead have a github action for it. We can control the environment of the runner for that action (i.e.: we can ensure the target directory will be found). The action will reside in our source tree, so folks can steal it if they want to DIY the generation.

Oh, that sounds like an good idea. Though I'm not good at github actions, maybe you can write it?

I've removed the commits with my try from the PR.

2024-06-23 23:26 UTC, isosphere commented
> Oh, that sounds like an good idea. Though I'm not good at github actions, maybe you can write it?

I can try; I'm no expert at it either; I've implemented them a couple of times with instructions.

2024-06-29 10:28 UTC, alexkazik commented
I was thinking about another problem and found another solution for this problem.

I've added it to this branch: https://github.com/alexkazik/yew-bootstrap/commits/update-icons2/
(Also I moved your commit to the beginning)

Before an merge I'd update the icons version again, to the then up to date.

2024-06-29 13:35 UTC, isosphere commented
`trunk serve` gives me a weird result for the `examples/icons` crate using https://github.com/alexkazik/yew-bootstrap/commit/693f0a13ed3b20d25b487ff4701b564e84bf8c20:

![image](https://github.com/isosphere/yew-bootstrap/assets/163370/04cfddf9-3a4d-4ddb-b5d8-85a832996ebb)

No 404 errors in the network trace:

![image](https://github.com/isosphere/yew-bootstrap/assets/163370/6795ba95-9af0-468e-97fd-7aa8765ad65a)

The hook did run:

```
2024-06-29T13:28:44.403601Z  INFO spawned hook cargo command_arguments=["run", "--bin", "include-bootstrap-icons"]
2024-06-29T13:28:44.403629Z  INFO spawning hook stage=PostBuild command=cargo
...
     Running `/home/matt/.cargo/build/debug/include-bootstrap-icons`
2024-06-29T13:29:01.310198Z  INFO finished hook cargo
2024-06-29T13:29:01.310256Z  INFO applying new distribution
2024-06-29T13:29:01.310948Z  INFO ✅ success
2024-06-29T13:29:01.311031Z  INFO 📡 serving static assets at -> /
```

2024-06-29 14:03 UTC, alexkazik commented
That's really weird.
<img width="830" alt="Screenshot 2024-06-29 at 16 01 33" src="https://github.com/isosphere/yew-bootstrap/assets/612453/fedd70ba-5ef6-4197-b976-62fa0d7c9dc2">

```
❯ trunk serve -v    
2024-06-29T14:00:07.387637Z  INFO 🚀 Starting trunk 0.20.2
2024-06-29T14:00:07.387947Z DEBUG Spawning update check
2024-06-29T14:00:07.388350Z DEBUG Performing update check
2024-06-29T14:00:07.388799Z DEBUG Disable error reporting: false
2024-06-29T14:00:07.388902Z DEBUG Time since last check: 17h23m22s70ms501µs
2024-06-29T14:00:07.388905Z DEBUG No refresh needed
2024-06-29T14:00:07.388891Z DEBUG Enforce version - actual: 0.20.2, required: *
2024-06-29T14:00:07.388921Z DEBUG Current: 0.20.2, Most recent: 0.20.2
2024-06-29T14:00:07.390438Z DEBUG Build cooldown: None
2024-06-29T14:00:07.390537Z  INFO 📦 starting build
2024-06-29T14:00:07.390711Z DEBUG spawning asset pipelines
2024-06-29T14:00:07.555498Z DEBUG building icons
2024-06-29T14:00:07.555511Z DEBUG cargo args args=["build", "--target=wasm32-unknown-unknown", "--manifest-path", "/Users/alx/Develop/Rust/yew-bootstrap/examples/icons/Cargo.toml", "--bin", "icons"]
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
warning: the following packages contain code that will be rejected by a future version of Rust: wasm-bindgen v0.2.87
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
2024-06-29T14:00:07.674113Z DEBUG fetching cargo artifacts
2024-06-29T14:00:07.751895Z DEBUG get: Getting tool app=WasmBindgen version=Some("0.2.87") offline=false client_options=HttpClientOptions { root_certificate: None, accept_invalid_certificates: false }
2024-06-29T14:00:07.761153Z DEBUG get:find_system: system version found for wasm-bindgen: 0.2.92 app=WasmBindgen version=Some("0.2.87") offline=false client_options=HttpClientOptions { root_certificate: None, accept_invalid_certificates: false } app=WasmBindgen
2024-06-29T14:00:07.761165Z  INFO get: tool version mismatch (required: 0.2.87, system: 0.2.92) app=WasmBindgen version=Some("0.2.87") offline=false client_options=HttpClientOptions { root_certificate: None, accept_invalid_certificates: false }
2024-06-29T14:00:07.761231Z DEBUG get: Using wasm-bindgen (0.2.87) from: /Users/alx/Library/Caches/dev.trunkrs.trunk/wasm-bindgen-0.2.87/wasm-bindgen app=WasmBindgen version=Some("0.2.87") offline=false client_options=HttpClientOptions { root_certificate: None, accept_invalid_certificates: false }
2024-06-29T14:00:07.761279Z DEBUG calling wasm-bindgen for icons
2024-06-29T14:00:07.761283Z DEBUG wasm-bindgen args args=["--target=web", "--out-dir=/Users/alx/.cargo/target/wasm-bindgen/debug", "--out-name=icons", "/Users/alx/.cargo/target/wasm32-unknown-unknown/debug/icons.wasm", "--no-typescript"]
2024-06-29T14:00:07.888368Z DEBUG copying generated wasm-bindgen artifacts
2024-06-29T14:00:07.888384Z DEBUG processing hash for /Users/alx/.cargo/target/wasm32-unknown-unknown/debug/icons.wasm
2024-06-29T14:00:07.893662Z DEBUG copying /Users/alx/.cargo/target/wasm-bindgen/debug/icons.js to /Users/alx/Develop/Rust/yew-bootstrap/examples/icons/dist/.stage/icons-e85d219f42bdb2ee.js
2024-06-29T14:00:07.893908Z DEBUG copying /Users/alx/.cargo/target/wasm-bindgen/debug/icons_bg.wasm to /Users/alx/Develop/Rust/yew-bootstrap/examples/icons/dist/.stage/icons-e85d219f42bdb2ee_bg.wasm
2024-06-29T14:00:07.894165Z DEBUG recording SRI record - type: Sha384. name: icons-e85d219f42bdb2ee.js, value: OutputDigest { integrity: Sha384, hash: "o+0e1T1xHh0iH19thsXTIVtMV6Q58Pid77EyOETmtpzHyzAUZxsAbzdIX5fmzN0m" }
2024-06-29T14:00:07.897193Z DEBUG recording SRI record - type: Sha384. name: icons-e85d219f42bdb2ee_bg.wasm, value: OutputDigest { integrity: Sha384, hash: "N/hVSpfR8n5SmTYdULdzL0c+aTvDL7ESKupdQKpHlCg0W8CcWT62+p7XrAfO6xYi" }
2024-06-29T14:00:07.897200Z DEBUG rust build complete
2024-06-29T14:00:07.897773Z  INFO spawned hook cargo command_arguments=["run", "--bin", "include-bootstrap-icons"]
2024-06-29T14:00:07.897788Z  INFO spawning hook stage=PostBuild command=cargo
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
warning: the following packages contain code that will be rejected by a future version of Rust: wasm-bindgen v0.2.87
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `/Users/alx/.cargo/target/debug/include-bootstrap-icons`
2024-06-29T14:00:08.184941Z  INFO finished hook cargo
2024-06-29T14:00:08.184987Z  INFO applying new distribution
2024-06-29T14:00:08.188623Z  INFO ✅ success
2024-06-29T14:00:08.188904Z  INFO 📡 serving static assets at -> /
2024-06-29T14:00:08.188974Z  INFO 📡 server listening at:
2024-06-29T14:00:08.188979Z  INFO     🏠 http://127.0.0.1:8080/
2024-06-29T14:00:08.188984Z  INFO     🏠 http://[::1]:8080/
```

btw. I now also moved my target directory to a global space.

2024-06-29 15:08 UTC, isosphere commented
My bad; my browser settings were set to ignore font selections other than what I had configured. Your new approach appears to work well!

2024-06-29 15:27 UTC, alexkazik commented
Good to hear. I would force push the new approach to this MR if that's ok.

2024-06-29 15:33 UTC, isosphere commented
> Good to hear. I would force push the new approach to this MR if that's ok.

Go for it; I'll kill the existing branch on my end to avoid a mess.

2024-06-29 16:02 UTC, alexkazik commented
Done. And I'm satisfies with this solution.

(Btw. I also tried to reduce the number of version numbers, but tried to use const str but that can't be used with concat, good idea with the macro.)

2024-06-29 18:29 UTC, isosphere commented
> Done. And I'm satisfied with this solution.

Great! I'll do a final check locally and then merge it. Thanks for your contribution, you've improved the way we handle icons. 

> (Btw. I also tried to reduce the number of version numbers, but tried to use const str but that can't be used with concat, good idea with the macro.)

It seemed like a maintainance nightmare, it had to die! I started with a `const str` too, took a few iterations before I arrived at that approach. I think I should brush up on macros, they can really cut down on repetition / boilerplate stuff.

2024-06-29 18:45 UTC, merged

2024-06-29 18:51 UTC, alexkazik commented
Glad to help - until next time (which should now be easier ;-)