Draft: Tooltips / Popper support
isosphere/yew-bootstrap pull request #46
Opened 2024-09-08 02:48 UTC by micolous

Based on #45 

This adds support for tooltips with [`popper-rs`](https://github.com/ctron/popper-rs/).

Bootstrap tooltips are built with Popper. Both Yew and Popper assume they have complete control of the DOM, so Popper needs some extra wiring to handle the component lifecycle correctly, which `popper-rs` provides.

This takes some ideas from [`react-bootstrap`'s Tooltip implementation](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Tooltip.tsx), but goes for a slightly simpler model, where Tooltips are dropped into a portal directly (like [`popper-rs`' example](https://github.com/ctron/popper-rs/blob/main/examples/yew/src/example/basic.rs)), and the Tooltip component is responsible for all the event handling (rather than [`Overlay`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Overlay.tsx) and [`OverlayTrigger`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayTrigger.tsx)).

To position the tooltip correctly and mark the target element with accessibility attributes, you need to expose a `NodeRef` for each component you want to add a tooltip to. I've exposed `NodeRef`s for `Button`, `FormControl` and `Link`.

Unlike regular Bootstrap, this doesn't support tooltips from `data` attributes.

I've added examples using all of those controls, and also a direct `ref=` attribute on a HTML elements.

2025-02-01 15:01 UTC, isosphere requested changes
Please correct the use of the `TooltipFocusTrigger` variants in the forms example. Looks like you may have changed the names and missed updating them.

2025-02-01 15:01 UTC, isosphere commented on examples/forms/src/main.rs
> +                                TooltipFocusTrigger::IfNoAnyHover,
These variants don't exist!

2025-04-18 00:41 UTC, micolous commented on examples/forms/src/main.rs
> +                                TooltipFocusTrigger::IfNoAnyHover,
Fixed

2025-04-18 00:43 UTC, micolous commented
Build failure in CI looks like it's running on a newer version of Rust which doesn't work with the old version of `wasm-bindgen`. Will have a look...

2025-04-18 01:08 UTC, micolous commented
Rebased on top of #52 to update old dependencies in `Cargo.lock`, that seems to fix the build.

2025-04-22 23:47 UTC, merged

2025-04-22 23:48 UTC, isosphere commented
The examples work great! Thanks for the valuable contribution.